apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-bigproject-deployment
  labels:
    app: docker-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
      - name: docker-k8s-demo
        image: prashk7/my-app
        ports:
        - containerPort: 8083